name: Prod Deployment

'on':
    push:
        branches:
            - develop
    pull_request:
        branches:
            - develop

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2
            
            -   name: Install Node.js
                uses: actions/setup-node@v1
                with:
                    node-version: 20.x
            
            -   name: Install node packages
                working-directory: ./source
                run: npm ci
            
            -   name: Create prod build
                working-directory: ./source
                run: npm run build            
            
            -   name: Upload prod build files
                uses: actions/upload-artifact@v2
                with:
                    name: production-files
                    path: ./source/build
    deploy:
        name: Deploy
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/develop'
        steps:
            -   name: Download artifact
                uses: actions/download-artifact@v2
                with:
                    name: production-files
                    path: ./source/build

            -   name: Deploy to gh-pages
                uses: peaceiris/actions-gh-pages@v3
                with:
                    deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                    publish_dir: ./source/build
